[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
sol_playground = "2J6X5c5Rk3yZfV7e37jzc7A3nomeoKM5fUEFxnEyAPvu"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/shrawanthakur/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
